In [1]:
from numpy import array

In [3]:
T = array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]],
])

In [4]:
print(T.shape)

(3, 3, 3)


In [5]:
print(T)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
